// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bdoProject.Infrastructure.Persistence;

#nullable disable

namespace bdoProject.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bdoProject.Domain.Entities.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentCode")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ProbationEndDate")
                        .HasColumnType("date");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 0,
                            DepartmentName = "აუდიტი და მარწმუნებელი მომსახურება",
                            Email = "nino.beridze@northstar.example",
                            EmployeeId = "E1001",
                            EmploymentType = 0,
                            FullName = "ნინო ბერიძე",
                            JobTitle = "უფროსი აუდიტორი",
                            ManagerId = "E1010",
                            ProbationEndDate = new DateOnly(2019, 6, 3),
                            Role = 1,
                            StartDate = new DateOnly(2019, 3, 4),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 1,
                            DepartmentName = "საკონსულტაციო მომსახურება",
                            Email = "aleksandre.kapanadze@northstar.example",
                            EmployeeId = "E1002",
                            EmploymentType = 0,
                            FullName = "ალექსანდრე კაპანაძე",
                            JobTitle = "კონსულტანტი",
                            ManagerId = "E1011",
                            ProbationEndDate = new DateOnly(2024, 9, 9),
                            Role = 1,
                            StartDate = new DateOnly(2024, 6, 10),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 2,
                            DepartmentName = "საგადასახადო მომსახურება",
                            Email = "ketevan.lomidze@northstar.example",
                            EmployeeId = "E1003",
                            EmploymentType = 0,
                            FullName = "ქეთევან ლომიძე",
                            JobTitle = "საგადასახადო მენეჯერი",
                            ManagerId = "E1012",
                            ProbationEndDate = new DateOnly(2014, 12, 14),
                            Role = 1,
                            StartDate = new DateOnly(2014, 9, 15),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 3,
                            DepartmentName = "ტექნოლოგიები და ავტომატიზაცია",
                            Email = "luka.tsiklauri@northstar.example",
                            EmployeeId = "E1004",
                            EmploymentType = 0,
                            FullName = "ლუკა წიკლაური",
                            JobTitle = "ავტომატიზაციის უმცროსი დეველოპერი",
                            ManagerId = "E1013",
                            ProbationEndDate = new DateOnly(2026, 11, 30),
                            Role = 1,
                            StartDate = new DateOnly(2026, 9, 1),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 0,
                            DepartmentName = "აუდიტი და მარწმუნებელი მომსახურება",
                            Email = "ana.gelashvili@northstar.example",
                            EmployeeId = "E1005",
                            EmploymentType = 0,
                            FullName = "ანა გელაშვილი",
                            JobTitle = "აუდიტის ასოცირებული სპეციალისტი",
                            ManagerId = "E1010",
                            ProbationEndDate = new DateOnly(2023, 4, 30),
                            Role = 1,
                            StartDate = new DateOnly(2023, 2, 1),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 1,
                            DepartmentName = "საკონსულტაციო მომსახურება",
                            Email = "davit.maisuradze@northstar.example",
                            EmployeeId = "E1006",
                            EmploymentType = 0,
                            FullName = "დავით მაისურაძე",
                            JobTitle = "უფროსი კონსულტანტი",
                            ManagerId = "E1011",
                            ProbationEndDate = new DateOnly(2021, 8, 16),
                            Role = 1,
                            StartDate = new DateOnly(2021, 5, 17),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 4,
                            DepartmentName = "ადამიანური რესურსების სამსახური",
                            Email = "tamar.jorjadze@northstar.example",
                            EmployeeId = "E1007",
                            EmploymentType = 0,
                            FullName = "თამარ ჯორჯაძე",
                            JobTitle = "HR ბიზნეს პარტნიორი",
                            ManagerId = "E1014",
                            ProbationEndDate = new DateOnly(2020, 4, 12),
                            Role = 0,
                            StartDate = new DateOnly(2020, 1, 13),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 5,
                            DepartmentName = "ფინანსები და ადმინისტრირება",
                            Email = "levan.abashidze@northstar.example",
                            EmployeeId = "E1008",
                            EmploymentType = 0,
                            FullName = "ლევან აბაშიძე",
                            JobTitle = "ბუღალტერი",
                            ManagerId = "E1014",
                            ProbationEndDate = new DateOnly(2022, 10, 31),
                            Role = 1,
                            StartDate = new DateOnly(2022, 8, 1),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 3,
                            DepartmentName = "ტექნოლოგიები და ავტომატიზაცია",
                            Email = "salome.khutsishvili@northstar.example",
                            EmployeeId = "E1009",
                            EmploymentType = 0,
                            FullName = "სალომე ხუციშვილი",
                            JobTitle = "ავტომატიზაციის კონსულტანტი",
                            ManagerId = "E1013",
                            ProbationEndDate = new DateOnly(2022, 4, 9),
                            Role = 1,
                            StartDate = new DateOnly(2022, 1, 10),
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 0,
                            DepartmentName = "აუდიტი და მარწმუნებელი მომსახურება",
                            Email = "irakli.nozadze@northstar.example",
                            EmployeeId = "E1010",
                            EmploymentType = 0,
                            FullName = "ირაკლი ნოზაძე",
                            JobTitle = "აუდიტის მენეჯერი",
                            ProbationEndDate = new DateOnly(2015, 6, 30),
                            Role = 1,
                            StartDate = new DateOnly(2015, 4, 1),
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 1,
                            DepartmentName = "საკონსულტაციო მომსახურება",
                            Email = "eka.chkheidze@northstar.example",
                            EmployeeId = "E1011",
                            EmploymentType = 0,
                            FullName = "ეკა ჩხეიძე",
                            JobTitle = "საკონსულტაციო მენეჯერი",
                            ProbationEndDate = new DateOnly(2018, 1, 1),
                            Role = 1,
                            StartDate = new DateOnly(2017, 10, 2),
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 2,
                            DepartmentName = "საგადასახადო მომსახურება",
                            Email = "beka.kavtaradze@northstar.example",
                            EmployeeId = "E1012",
                            EmploymentType = 0,
                            FullName = "ბექა ქავთარაძე",
                            JobTitle = "საგადასახადო დირექტორი",
                            ProbationEndDate = new DateOnly(2013, 6, 17),
                            Role = 1,
                            StartDate = new DateOnly(2013, 3, 18),
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 3,
                            DepartmentName = "ტექნოლოგიები და ავტომატიზაცია",
                            Email = "teona.gogoladze@northstar.example",
                            EmployeeId = "E1013",
                            EmploymentType = 0,
                            FullName = "თეონა გოგოლაძე",
                            JobTitle = "ავტომატიზაციის მენეჯერი",
                            ProbationEndDate = new DateOnly(2018, 5, 18),
                            Role = 1,
                            StartDate = new DateOnly(2018, 2, 19),
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = 5,
                            DepartmentName = "ფინანსები და ადმინისტრირება",
                            Email = "nika.shengelia@northstar.example",
                            EmployeeId = "E1014",
                            EmploymentType = 0,
                            FullName = "ნიკა შენგელია",
                            JobTitle = "ფინანსური დირექტორი",
                            ProbationEndDate = new DateOnly(2016, 9, 5),
                            Role = 1,
                            StartDate = new DateOnly(2016, 6, 6),
                            Status = 0
                        });
                });

            modelBuilder.Entity("bdoProject.Domain.Entities.Holidays.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 1),
                            Name = "ახალი წელი"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 2),
                            Name = "ახალი წელი"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 7),
                            Name = "შობა"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 19),
                            Name = "ნათლისღება"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 3),
                            Name = "დედის დღე"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 8),
                            Name = "ქალთა საერთაშორისო დღე"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 9),
                            Name = "ეროვნული ერთიანობის დღე"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 10),
                            Name = "დიდი პარასკევი"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 11),
                            Name = "დიდი შაბათი"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 12),
                            Name = "აღდგომა"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 13),
                            Name = "აღდგომის ორშაბათი"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 5, 9),
                            Name = "ფაშიზმზე გამარჯვების დღე"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 5, 12),
                            Name = "წმინდა ანდრია პირველწოდებულის დღე"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 5, 26),
                            Name = "დამოუკიდებლობის დღე"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 8, 28),
                            Name = "მარიამობა"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 10, 14),
                            Name = "სვეტიცხოვლობა"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 11, 23),
                            Name = "გიორგობა"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 1, 1),
                            Name = "ახალი წელი"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 1, 2),
                            Name = "ახალი წელი"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 1, 7),
                            Name = "შობა"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 1, 19),
                            Name = "ნათლისღება"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 3, 3),
                            Name = "დედის დღე"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 3, 8),
                            Name = "ქალთა საერთაშორისო დღე"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 4, 9),
                            Name = "ეროვნული ერთიანობის დღე"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 4, 30),
                            Name = "დიდი პარასკევი"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 1),
                            Name = "დიდი შაბათი"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 2),
                            Name = "აღდგომა"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 3),
                            Name = "აღდგომის ორშაბათი"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 9),
                            Name = "ფაშიზმზე გამარჯვების დღე"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 12),
                            Name = "წმინდა ანდრია პირველწოდებულის დღე"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 5, 26),
                            Name = "დამოუკიდებლობის დღე"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 8, 28),
                            Name = "მარიამობა"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 10, 14),
                            Name = "სვეტიცხოვლობა"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2027, 11, 23),
                            Name = "გიორგობა"
                        });
                });

            modelBuilder.Entity("bdoProject.Domain.Entities.LeaveAndAbsence.LeaveEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarriedOverDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntitledDays")
                        .HasColumnType("integer");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LeaveEntitlements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarriedOverDays = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1001",
                            EntitledDays = 25,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1001",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1001",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1001",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1002",
                            EntitledDays = 24,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1002",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 7,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1002",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1002",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 9,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1003",
                            EntitledDays = 26,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 10,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1003",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 11,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1003",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 12,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1003",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 13,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1004",
                            EntitledDays = 8,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 14,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1004",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 15,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1004",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 16,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1004",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 17,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1005",
                            EntitledDays = 24,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 18,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1005",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 19,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1005",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 20,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1005",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 21,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1006",
                            EntitledDays = 25,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 22,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1006",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 23,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1006",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 24,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1006",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 25,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1007",
                            EntitledDays = 25,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 26,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1007",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 27,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1007",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 28,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1007",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 29,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1008",
                            EntitledDays = 24,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 30,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1008",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 31,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1008",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 32,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1008",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 33,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1009",
                            EntitledDays = 24,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 34,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1009",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 35,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1009",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 36,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1009",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 37,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1010",
                            EntitledDays = 26,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 38,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1010",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 39,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1010",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 40,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1010",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 41,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1011",
                            EntitledDays = 25,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 42,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1011",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 43,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1011",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 44,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1011",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 45,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1012",
                            EntitledDays = 26,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 46,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1012",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 47,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1012",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 48,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1012",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 49,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1013",
                            EntitledDays = 25,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 50,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1013",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 51,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1013",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 52,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1013",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 53,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1014",
                            EntitledDays = 26,
                            LeaveType = 0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 54,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1014",
                            EntitledDays = 10,
                            LeaveType = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 55,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1014",
                            EntitledDays = 5,
                            LeaveType = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 56,
                            CarriedOverDays = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "E1014",
                            EntitledDays = 30,
                            LeaveType = 2,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("bdoProject.Domain.Entities.LeaveAndAbsence.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedVia")
                        .HasColumnType("integer");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "პროექტის პარტნიორის თანხმობით",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1001",
                            EndDate = new DateOnly(2026, 2, 20),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 2, 16),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 2,
                            EmployeeId = "E1001",
                            EndDate = new DateOnly(2026, 3, 11),
                            LeaveType = 1,
                            StartDate = new DateOnly(2026, 3, 10),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "გაუქმებულია თანამშრომლის მიერ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 2,
                            EmployeeId = "E1001",
                            EndDate = new DateOnly(2026, 5, 5),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 5, 4),
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1001",
                            EndDate = new DateOnly(2026, 7, 24),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 7, 13),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 3,
                            EmployeeId = "E1001",
                            EndDate = new DateOnly(2026, 11, 11),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 11, 9),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1002",
                            EndDate = new DateOnly(2026, 5, 8),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 5, 4),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Comment = "ხელმძღვანელის თანხმობით, 15 სამუშაო დღე",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 15,
                            EmployeeId = "E1002",
                            EndDate = new DateOnly(2026, 8, 21),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 8, 3),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Comment = "უარყოფილია: კლიენტის პროექტის ვადა",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1002",
                            EndDate = new DateOnly(2026, 10, 30),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 10, 26),
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 3,
                            EmployeeId = "E1003",
                            EndDate = new DateOnly(2026, 4, 8),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 4, 6),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1003",
                            EndDate = new DateOnly(2026, 6, 19),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 6, 15),
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 3,
                            EmployeeId = "E1003",
                            EndDate = new DateOnly(2026, 8, 12),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 8, 10),
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1005",
                            EndDate = new DateOnly(2026, 3, 27),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 3, 23),
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 4,
                            EmployeeId = "E1005",
                            EndDate = new DateOnly(2026, 8, 28),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 8, 24),
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1006",
                            EndDate = new DateOnly(2026, 7, 17),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 7, 6),
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 3,
                            EmployeeId = "E1006",
                            EndDate = new DateOnly(2026, 11, 18),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 11, 16),
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1007",
                            EndDate = new DateOnly(2026, 6, 12),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1008",
                            EndDate = new DateOnly(2026, 7, 31),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 7, 20),
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 2,
                            EmployeeId = "E1008",
                            EndDate = new DateOnly(2026, 9, 15),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 9, 14),
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 2,
                            EmployeeId = "E1009",
                            EndDate = new DateOnly(2026, 1, 21),
                            LeaveType = 1,
                            StartDate = new DateOnly(2026, 1, 20),
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 4,
                            EmployeeId = "E1009",
                            EndDate = new DateOnly(2026, 4, 17),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 4, 14),
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Comment = "AZ-900 გამოცდა",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 1,
                            EmployeeId = "E1009",
                            EndDate = new DateOnly(2026, 6, 5),
                            LeaveType = 4,
                            StartDate = new DateOnly(2026, 6, 5),
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 8,
                            EmployeeId = "E1009",
                            EndDate = new DateOnly(2026, 8, 26),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 8, 17),
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 9,
                            EmployeeId = "E1010",
                            EndDate = new DateOnly(2026, 4, 30),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 4, 20),
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1011",
                            EndDate = new DateOnly(2026, 8, 21),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 8, 10),
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1012",
                            EndDate = new DateOnly(2026, 8, 7),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 7, 27),
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 5,
                            EmployeeId = "E1013",
                            EndDate = new DateOnly(2026, 9, 25),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 9, 21),
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedVia = 0,
                            Days = 10,
                            EmployeeId = "E1014",
                            EndDate = new DateOnly(2026, 7, 3),
                            LeaveType = 0,
                            StartDate = new DateOnly(2026, 6, 22),
                            Status = 1
                        });
                });

            modelBuilder.Entity("bdoProject.Domain.Entities.LeaveAndAbsence.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnualLimitDays")
                        .HasColumnType("integer");

                    b.Property<int>("AssistantSupported")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayUnit")
                        .HasColumnType("integer");

                    b.Property<int>("LeaveTypes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SelfService")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssistantSupported = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 0,
                            LeaveTypes = 0,
                            Name = "ყოველწლიური ანაზღაურებადი შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 4",
                            SelfService = 1
                        },
                        new
                        {
                            Id = 2,
                            AnnualLimitDays = 10,
                            AssistantSupported = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 0,
                            LeaveTypes = 1,
                            Name = "ავადმყოფობის შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 6",
                            SelfService = 1
                        },
                        new
                        {
                            Id = 3,
                            AnnualLimitDays = 30,
                            AssistantSupported = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 1,
                            LeaveTypes = 2,
                            Name = "უხელფასო შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 7",
                            SelfService = 1
                        },
                        new
                        {
                            Id = 4,
                            AssistantSupported = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 0,
                            LeaveTypes = 3,
                            Name = "გლოვის შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 8",
                            SelfService = 1
                        },
                        new
                        {
                            Id = 5,
                            AnnualLimitDays = 5,
                            AssistantSupported = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 0,
                            LeaveTypes = 4,
                            Name = "სასწავლო და საგამოცდო შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 9",
                            SelfService = 1
                        },
                        new
                        {
                            Id = 6,
                            AssistantSupported = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayUnit = 2,
                            LeaveTypes = 5,
                            Name = "მშობლის შვებულება",
                            PolicyReference = "შვებულებისა და გაცდენის პოლიტიკა, მუხლი 10",
                            SelfService = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
